[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
source = "."
name = "propertyiq-api"

[services.variables]
PORT = "8000"
HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"